[package]
name = "rust_company_directory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jammdb = "0.5.0"
serde = "1.0.130"
rmp-serde = "0.15.5"